server:
  port: 8080

spring:
  application:
    name: occupational-safety-and-health-app
  profiles:
    active: "@profileActive@"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5444/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    #initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  liquibase:
#    change-log: classpath:db.changelog/db.changelog-master.xml
#    enabled: true
#    default-schema: company_hierarchy
app:
  rest:
    url: /api/v1
  auth:
    antMatchers:
      - /**
      - ${app.rest.url}/login
      - ${app.rest.url}/checkLogin
      - ${app.rest.url}/registration/**
      - /h2-console/**


jwt:
  headerName: Auth-Token
  expirationHours: 1

logging:
  level:
    org.springframework: ${SPRING_LOG_LEVEL:ERROR}
    com.netflix: ${NETFLIX_LOG_LEVEL:ERROR}
    eu.senla: ${LOG_LEVEL:TRACE}
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger - %msg%n"
