server:
  port: 8080

spring:
  application:
    name: occupational-safety-and-health-app
  profiles:
    active:
      - "@generationStrategyProfile@"
      - "@startMode@"

app:
  version: 0.0.1
  rest:
    url: /api/v1
  auth:
    antMatchers:
      - /**
      - ${app.rest.url}/login
      - ${app.rest.url}/checkLogin
      - ${app.rest.url}/registration/**
      - ${springdoc.swagger-ui.path}
      - /swagger-ui/**
      - /v3/api-docs/**
      - /h2-console/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  headerName: Auth-Token
  expirationHours: 1

logging:
  level:
    org.springframework: info
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger - %msg%n"