server:
  port: 8080

spring:
  application:
    name: occupational-safety-and-health-app
  profiles:
    active: "@profileActive@"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://test_postgres_db:5333/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

app:
  version: 0.0.1
  rest:
    url: /api/v1
  auth:
    antMatchers:
      - /**
      - ${app.rest.url}/login
      - ${app.rest.url}/checkLogin
      - ${app.rest.url}/registration/**
      - ${springdoc.swagger-ui.path}
      - /swagger-ui/**
      - /v3/api-docs/**
      - /h2-console/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  headerName: Auth-Token
  expirationHours: 1

logging:
  level:
    org.springframework: ${SPRING_LOG_LEVEL:ERROR}
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger - %msg%n"
