version: '3.7'

services:
#  occupational-safety-and-health-app:
#    container_name: osh-app
#    build:
#      context: ./rest/
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8080"
#    depends_on:
#      - postgres_db

  postgres_db:
    container_name: test_postgres_db
    image: postgres:12-alpine
    ports:
      - "5444:5333"
    volumes:
      - /home/mark/Documents/Repo/My/occupational-safety-and-health-app/database/postgres-volume:/var/lib/postgresql/data/
    environment:
      - PGPORT=5333
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped

  liquibase:
    container_name: test_liquibase
    image: liquibase/liquibase:4.4
    depends_on:
      - postgres_db
    volumes:
      - /home/mark/Documents/Repo/My/occupational-safety-and-health-app/database/liquibase/changelog:/liquibase/changelog
    command: ['--driver=org.postgresql.Driver',
              '--url=jdbc:postgresql://test_postgres_db:5333/postgres',
              '--changeLogFile=xml/db.changelog-master.xml',
              '--username=postgres',
              '--password=postgres',
              'update']
    restart: "no"