version: '3.7'

services:

  postgres_db:
    container_name: test_postgres_db
    image: postgres:12-alpine
    ports:
      - "5444:5333"
    volumes:
      - /home/mark/docker-storage/databases/test_postgres_db:/var/lib/postgresql/data/
    environment:
      - PGPORT=5333
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
