version: '3.7'

services:
  occupational-safety-and-health-app:
    container_name: osh-app
    build:
      context: ./rest/
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres_db
      - liquibase

  postgres_db:
    container_name: test_postgres_db
    image: postgres:12-alpine
    ports:
      - "5444:5333"
    volumes:
      - ./database/postgres-volume:/var/lib/postgresql/data/
    env_file:
      - .env.postgres
    restart: unless-stopped

  liquibase:
    container_name: liquibase_changelog_executor
    image: liquibase/liquibase:4.4
    depends_on:
      - postgres_db
    volumes:
      - ./database/liquibase/changelog:/liquibase/changelog
    command: ['--driver=org.postgresql.Driver',
              '--url=${DB_URL}',
              '--changeLogFile=xml/db.changelog-master.xml',
              '--username=${DB_USER}',
              '--password=${DB_PASSWORD}',
              'update']
    restart: "no"